We have next massage:2022-11-05 17:02:28,446:ERROR:Exception
Traceback (most recent call last):
  File "D:\denrtf\RTF\p8_2.py", line 9, in <module>
    print(10/0)
ZeroDivisionError: division by zero
